# Generated by Django 4.0 on 2022-02-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
